baseURL = "https://erichen0208.github.io/"
languageCode = "zh-tw"
title = "Eric Blog"
theme = "PaperMod"
enableRobotsTXT = true

[pagination]
  pagerSize = 5

[params]

  mainSections = ["posts"]

  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = true
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

  [params.assets]
    customCSS = ["css/custom.css"]
    disableFingerprinting = true

[menu]

  [[menu.main]]
    identifier = "posts"
    name = "首頁"
    url = ""
    weight = 1

  [[menu.main]]
    identifier = "portfolio"
    name = "攝影集"
    url = "/portfolio/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "關於我"
    url = "/about/"
    weight = 3

[taxonomies]
  tag = "tags"
  category = "categories"
